export const DEFAULT_PROFILE_IMAGE = process.env.REACT_APP_DEFAULT_PROFILE_IMAGE;
export const LEAF_USER_BASE_URL = process.env.REACT_APP_LEAF_USER_BASE_URL;
export const LEAF_PROFILE_REFRESH_TOKEN_URL = process.env.REACT_APP_LEAF_PROFILE_REFRESH_TOKEN_URL;
export const LEAF_POST_BASE_URL = process.env.REACT_APP_LEAF_POST_BASE_URL;